spring:
  application:
    name: DeptService
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:8761/
server:
  port: 2222
management:
  endpoints:
    web:
      exposure:
        include: '*'
